// src/app/app.component.ts
import { Component } from '@angular/core';

import { HeaderComponent } from './components/header/header.component';
import { MessageEditorComponent } from './components/message-editor/message-editor.component';
import { SegmentDetailComponent } from './components/segment-detail/segment-detail.component';

@Component({
  selector: 'app-root',
  imports: [HeaderComponent, MessageEditorComponent, SegmentDetailComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  public selectedLineContent = '';
  public selectedLineIndex = -1;
  public hl7Message = '';

  public onLineSelected(event: {
    lineContent: string;
    lineIndex: number;
  }): void {
    this.selectedLineContent = event.lineContent;
    this.selectedLineIndex = event.lineIndex;
  }

  public onMessageChanged(message: string): void {
    this.hl7Message = message;
  }

  public onFieldValueChange(event: {
    lineIndex: number;
    fieldIndex: number;
    componentIndex: number | null;
    newValue: string;
  }): void {
    const lines = this.hl7Message.split(/\r\n|\r|\n/);
    const line = lines[event.lineIndex];

    if (!line) return;

    const segName = line.substring(0, 3);
    let fields: string[];

    if (segName === 'MSH') {
      const sep = line[3] || '|';
      const rest = line.substring(4).split(sep);

      fields = [sep, ...rest];
    } else {
      fields = line.split('|').slice(1);
    }

    // Update the field value
    if (event.componentIndex !== null) {
      // Update component in composite field
      const comps = fields[event.fieldIndex].split('^');

      comps[event.componentIndex] = event.newValue;
      fields[event.fieldIndex] = comps.join('^');
    } else {
      // Update simple field
      fields[event.fieldIndex] = event.newValue;
    }

    // Rebuild the line
    let newLine: string;

    if (segName === 'MSH') {
      const sep = fields[0];

      newLine = 'MSH' + sep + fields.slice(1).join(sep);
    } else {
      newLine = segName + '|' + fields.join('|');
    }

    // Update the message
    lines[event.lineIndex] = newLine;
    this.hl7Message = lines.join('\n');
    // Update the selected line content
    this.selectedLineContent = newLine;
  }
}

<app-header></app-header>

<div class="w-full flex flex-col lg:flex-row flex-1 overflow-hidden">
  <div class="w-full lg:w-3/4 h-1/3 lg:h-full">
    <app-message-editor
      (lineSelected)="onLineSelected($event)"
      (messageChanged)="onMessageChanged($event)"></app-message-editor>
  </div>

  <div class="w-full lg:w-1/4 h-2/3 lg:h-full">
    <app-segment-detail
      [lineContent]="selectedLineContent"
      [lineIndex]="selectedLineIndex"
      (fieldValueChange)="onFieldValueChange($event)"></app-segment-detail>
  </div>
</div>

// src/App.jsx
import { useState } from "react";
import Header from "./components/Header";
import MessageEditor from "./components/MessageEditor";
import DetailPanel from "./components/DetailPanel";
import "./index.css";

function App() {
  const [message, setMessage] = useState("");
  const [currentLineIdx, setCurrentLineIdx] = useState(-1);
  const [theme, setTheme] = useState("dark");

  const handleFieldUpdate = (lineIdx, fieldIdx, compIdx, newValue) => {
    const lines = message.split(/\r\n|\r|\n/);
    const line = lines[lineIdx];
    const segName = line.substring(0, 3);
    let fields;

    if (segName === "MSH") {
      const sep = line[3] || "|";
      const rest = line.substring(4).split(sep);
      fields = [sep, ...rest];
    } else {
      fields = line.split("|").slice(1);
    }

    // Update the field value
    if (compIdx !== null) {
      // Update component in composite field
      const comps = fields[fieldIdx].split("^");
      comps[compIdx] = newValue;
      fields[fieldIdx] = comps.join("^");
    } else {
      // Update simple field
      fields[fieldIdx] = newValue;
    }

    // Rebuild the line
    let newLine;
    if (segName === "MSH") {
      const sep = fields[0];
      newLine = "MSH" + sep + fields.slice(1).join(sep);
    } else {
      newLine = segName + "|" + fields.join("|");
    }

    // Update the message
    lines[lineIdx] = newLine;
    setMessage(lines.join("\n"));
  };

  return (
    <div className="bg-custom-bg text-custom-text font-mono h-screen flex flex-col overflow-hidden">
      <Header theme={theme} setTheme={setTheme} />
      <div className="flex flex-col lg:flex-row flex-1 overflow-hidden">
        <MessageEditor
          message={message}
          setMessage={setMessage}
          currentLineIdx={currentLineIdx}
          setCurrentLineIdx={setCurrentLineIdx}
        />
        <DetailPanel
          message={message}
          currentLineIdx={currentLineIdx}
          onFieldUpdate={handleFieldUpdate}
        />
      </div>
    </div>
  );
}

export default App;
